# This is a basic workflow to help you get started with Actions

name: django-docker-image-build-and-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
    paths:
    - jupyterlab/optimizacion_2/3.1.0/Dockerfile #path in repo to Dockerfile

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: jupyterlab/optimizacion_2/3.1.0/Dockerfile #path in repo to Dockerfile
          platforms: linux/amd64
          push: true
          tags: palmoreck/jupyterlab_optimizacion_2:3.1.0
